services:
  # Nginx Reverse Proxy with SSL/TLS
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: voyageur-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend
    networks:
      - voyageur-network
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=443
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: voyageur-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # Optional: for database backups
    environment:
      - POSTGRES_DB=${DB_NAME:-voyageur_compass_db}
      - POSTGRES_USER=${DB_USER:-voyageur_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-ab727492Z}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-voyageur_user} -d ${POSTGRES_DB:-voyageur_compass_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voyageur-network

  # Redis Cache Service
  redis:
    image: redis:alpine
    container_name: voyageur-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voyageur-network

  # Django Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voyageur-backend
    restart: unless-stopped
    volumes:
      # Mount entire project for hot-reloading
      - .:/app:delegated
      # Prevent node_modules from frontend being copied
      - /app/Design/frontend/node_modules
      # Use named volume for static files
      - static_volume:/app/staticfiles
      - media_volume:/app/Design/media
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-False}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Security settings
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-False}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-False}
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-False}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-}
      - SECURE_HSTS_SECONDS=${SECURE_HSTS_SECONDS:-0}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Database is ready!' &&
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 1; done &&
        echo 'Redis is ready!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - voyageur-network

  # Celery Worker Service
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voyageur-celery-worker
    restart: unless-stopped
    volumes:
      # Mount entire project
      - .:/app:delegated
      # Prevent node_modules from frontend being copied
      - /app/Design/frontend/node_modules
      # Share media volume with backend
      - media_volume:/app/Design/media
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-False}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - C_FORCE_ROOT=true  # Allow celery to run as root in container
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 1; done &&
        echo 'Starting Celery Worker...' &&
        celery -A VoyageurCompass worker -l info --concurrency=2
      "
    networks:
      - voyageur-network

  # Celery Beat Scheduler Service
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voyageur-celery-beat
    restart: unless-stopped
    volumes:
      # Mount entire project
      - .:/app:delegated
      # Prevent node_modules from frontend being copied
      - /app/Design/frontend/node_modules
      # Celery beat schedule file
      - celerybeat_schedule:/app/celerybeat-schedule
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-False}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 1; done &&
        echo 'Starting Celery Beat...' &&
        celery -A VoyageurCompass beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    networks:
      - voyageur-network

  # React Frontend Service (Vite)
  frontend:
    build:
      context: ./Design/frontend
      dockerfile: Dockerfile
    container_name: voyageur-frontend
    restart: unless-stopped
    volumes:
      # Mount frontend source for hot-reloading
      - ./Design/frontend:/app:delegated
      # Use anonymous volume for node_modules to prevent conflicts
      - /app/node_modules
    expose:
      - "3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true  # For file watching on Windows
      - CHOKIDAR_USEPOLLING=true  # For hot reload on Windows
    depends_on:
      - backend
    stdin_open: true  # Keep STDIN open
    tty: true  # Allocate a pseudo-TTY
    networks:
      - voyageur-network

# Named volumes for data persistence
volumes:
  postgres_data:
    name: voyageur_postgres_data
  redis_data:
    name: voyageur_redis_data
  static_volume:
    name: voyageur_static
  media_volume:
    name: voyageur_media
  celerybeat_schedule:
    name: voyageur_celerybeat_schedule

# Custom network for service communication
networks:
  voyageur-network:
    name: voyageur-network
    driver: bridge