# Generated by Django 5.2.5 on 2025-08-14 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(db_index=True, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('logout', 'User Logout'), ('timeout', 'Session Timeout'), ('password_change', 'Password Change'), ('admin_action', 'Admin Action')], default='logout', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted Token',
                'verbose_name_plural': 'Blacklisted Tokens',
                'db_table': 'core_blacklisted_token',
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['token'], name='core_blackl_token_a41112_idx'), models.Index(fields=['expires_at'], name='core_blackl_expires_0c679a_idx')],
            },
        ),
    ]
