# Generated by Django 5.2.5 on 2025-08-09 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioholding",
            options={
                "ordering": ["-current_value"],
                "verbose_name": "Portfolio Holding",
                "verbose_name_plural": "Portfolio Holdings",
            },
        ),
        migrations.RemoveIndex(
            model_name="stockprice",
            name="Data_stockp_date_2b6b19_idx",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="user",
        ),
        migrations.RemoveField(
            model_name="portfolioholding",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="portfolioholding",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="stockprice",
            name="change_amount",
        ),
        migrations.RemoveField(
            model_name="stockprice",
            name="change_percent",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current portfolio value",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="initial_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Initial investment amount",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="risk_tolerance",
            field=models.CharField(
                choices=[("conservative", "Conservative"), ("moderate", "Moderate"), ("aggressive", "Aggressive")],
                default="moderate",
                help_text="Risk tolerance level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="average_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Average purchase price per share",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="cost_basis",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total investment cost",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="current_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current market price per share",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current market value",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this holding is active"),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="unrealized_gain_loss",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Unrealized profit/loss", max_digits=12),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="unrealized_gain_loss_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Unrealized profit/loss percentage", max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="portfolioholding",
            name="portfolio",
            field=models.ForeignKey(
                help_text="Parent portfolio",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="Data.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioholding",
            name="purchase_date",
            field=models.DateField(help_text="Date of initial purchase"),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="adjusted_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Adjusted closing price (accounts for splits, dividends)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="high",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Highest price of the day",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="low",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Lowest price of the day",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockprice",
            name="volume",
            field=models.BigIntegerField(default=0, help_text="Trading volume"),
        ),
        migrations.AddIndex(
            model_name="stockprice",
            index=models.Index(fields=["date"], name="Data_stockp_date_2c9b49_idx"),
        ),
    ]
