# Generated by Django 5.2.5 on 2025-08-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0012_dataindustryprice_averagevolume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(help_text='Analysis timestamp')),
                ('horizon', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('blend', 'Blend')], default='blend', help_text='Analysis time horizon', max_length=16)),
                ('w_sma50vs200', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted SMA 50/200 crossover score', max_digits=10, null=True)),
                ('w_pricevs50', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted price vs 50-day SMA score', max_digits=10, null=True)),
                ('w_rsi14', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted RSI(14) score', max_digits=10, null=True)),
                ('w_macd12269', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted MACD(12,26,9) histogram score', max_digits=10, null=True)),
                ('w_bbpos20', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Bollinger %B (20,2) score', max_digits=10, null=True)),
                ('w_bbwidth20', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Bollinger Bandwidth (20,2) score', max_digits=10, null=True)),
                ('w_volsurge', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Volume Surge score', max_digits=10, null=True)),
                ('w_obv20', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted OBV 20-day trend score', max_digits=10, null=True)),
                ('w_rel1y', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Relative Strength 1Y score', max_digits=10, null=True)),
                ('w_rel3y', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Relative Strength 3Y score', max_digits=10, null=True)),
                ('w_candlerev', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Candlestick Reversal score', max_digits=10, null=True)),
                ('w_srcontext', models.DecimalField(blank=True, decimal_places=6, help_text='Weighted Support/Resistance Context score', max_digits=10, null=True)),
                ('components', models.JSONField(default=dict, help_text='Raw and normalized values per indicator: {name: {raw: value, score: normalized_value}}')),
                ('composite_raw', models.DecimalField(blank=True, decimal_places=6, help_text='Sum of all weighted scores', max_digits=10, null=True)),
                ('score_0_10', models.IntegerField(blank=True, help_text='Final composite score (0-10, rounded)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(help_text='Related stock', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_results', to='Data.stock')),
            ],
            options={
                'verbose_name': 'Analytics Result',
                'verbose_name_plural': 'Analytics Results',
                'db_table': 'analytics_results',
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['stock', '-as_of'], name='analytics_r_stock_i_526010_idx'), models.Index(fields=['as_of'], name='analytics_r_as_of_bd71b7_idx'), models.Index(fields=['stock', 'horizon', '-as_of'], name='analytics_r_stock_i_007d8e_idx')],
                'unique_together': {('stock', 'as_of')},
            },
        ),
    ]
