# Generated by Django 5.2.5 on 2025-08-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0016_add_analytics_results_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsresults',
            name='lastNewsDate',
            field=models.DateTimeField(blank=True, help_text='Date of most recent news article analyzed', null=True),
        ),
        migrations.AddField(
            model_name='analyticsresults',
            name='newsCount',
            field=models.IntegerField(blank=True, default=0, help_text='Number of news articles analyzed for sentiment', null=True),
        ),
        migrations.AddField(
            model_name='analyticsresults',
            name='sentimentConfidence',
            field=models.FloatField(blank=True, help_text='Sentiment analysis confidence score (0 to 1)', null=True),
        ),
        migrations.AddField(
            model_name='analyticsresults',
            name='sentimentLabel',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Sentiment classification label', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresults',
            name='sentimentScore',
            field=models.FloatField(blank=True, help_text='Sentiment score (-1 to 1, where -1 is most negative, 1 is most positive)', null=True),
        ),
        migrations.AddField(
            model_name='analyticsresults',
            name='sentimentSources',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of sentiment by source: {source: {count: n, avg_score: float}}'),
        ),
    ]
