# Generated by Django 5.2.5 on 2025-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0017_add_sentiment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsresults",
            name="model_version",
            field=models.CharField(
                blank=True, help_text="Version of LSTM model used for predictions", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="analyticsresults",
            name="prediction_1d",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="1-day price prediction from LSTM model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsresults",
            name="prediction_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="30-day price prediction from LSTM model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsresults",
            name="prediction_7d",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="7-day price prediction from LSTM model",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsresults",
            name="prediction_confidence",
            field=models.FloatField(blank=True, help_text="Confidence score for LSTM predictions (0.0-1.0)", null=True),
        ),
        migrations.AddField(
            model_name="analyticsresults",
            name="prediction_timestamp",
            field=models.DateTimeField(blank=True, help_text="Timestamp when predictions were generated", null=True),
        ),
    ]
