# Generated by Django 5.2.5 on 2025-09-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0019_add_explanation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Stock ticker symbol (e.g., AAPL, MSFT). Extended length supports test symbols.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
