# Generated by Django 5.2.5 on 2025-09-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0023_add_performance_indexes'),
        ('Data', '0021_add_yahoo_cache_model'),
    ]

    operations = [
    ]
