# Generated by Django 5.2.5 on 2025-09-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0022_merge_20250912_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='data',
            field=models.JSONField(help_text='Cached Yahoo Finance API response data'),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='data_type',
            field=models.CharField(choices=[('info', 'Stock Info'), ('history', 'Price History'), ('financials', 'Financials')], help_text='Type of Yahoo Finance data cached', max_length=20),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if fetch failed', null=True),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='expires_at',
            field=models.DateTimeField(help_text='When this cached data expires'),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='fetch_success',
            field=models.BooleanField(default=True, help_text='Whether the API fetch was successful'),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='period',
            field=models.CharField(help_text='Data period (e.g., 1y, 3mo, max)', max_length=10),
        ),
        migrations.AlterField(
            model_name='yahoofinancecache',
            name='symbol',
            field=models.CharField(db_index=True, help_text='Stock symbol (e.g., AAPL)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='yahoofinancecache',
            unique_together={('symbol', 'period', 'data_type')},
        ),
    ]
