services:
  db:
    image: postgres:15-alpine
    container_name: voyageur-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - POSTGRES_DB=${DB_NAME:-voyageur_compass_db}
      - POSTGRES_USER=${DB_USER:-voyageur_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-voyageur_user} -d ${DB_NAME:-voyageur_compass_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voyageur-network

  redis:
    image: redis:alpine
    container_name: voyageur-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - voyageur-network

  ollama:
    image: ollama/ollama:latest
    container_name: voyageur-ollama
    restart: unless-stopped
    profiles: ["gpu"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-1}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}
      - OLLAMA_GPU_MEMORY_FRACTION=${OLLAMA_GPU_MEMORY_FRACTION:-0.8}
      - CUDA_VISIBLE_DEVICES=0
      # Multi-model configuration
      - OLLAMA_SUMMARY_MODEL=${OLLAMA_SUMMARY_MODEL:-phi3:3.8b}
      - OLLAMA_STANDARD_MODEL=${OLLAMA_STANDARD_MODEL:-phi3:3.8b}  
      - OLLAMA_DETAILED_MODEL=${OLLAMA_DETAILED_MODEL:-llama3.1:8b}
      - OLLAMA_TRANSLATION_MODEL=${OLLAMA_TRANSLATION_MODEL:-qwen2:7b}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - voyageur-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
          memory: 16G
        limits:
          memory: 64G

  # CPU-only Ollama fallback
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: voyageur-ollama-cpu
    restart: unless-stopped
    profiles: ["cpu"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-1}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}
      # Multi-model configuration
      - OLLAMA_SUMMARY_MODEL=${OLLAMA_SUMMARY_MODEL:-phi3:3.8b}
      - OLLAMA_STANDARD_MODEL=${OLLAMA_STANDARD_MODEL:-phi3:3.8b}  
      - OLLAMA_DETAILED_MODEL=${OLLAMA_DETAILED_MODEL:-llama3.1:8b}
      - OLLAMA_TRANSLATION_MODEL=${OLLAMA_TRANSLATION_MODEL:-qwen2:7b}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - voyageur-network

volumes:
  postgres_data:
    name: voyageur_postgres_data
  redis_data:
    name: voyageur_redis_data
  ollama_data:
    name: voyageur_ollama_data

networks:
  voyageur-network:
    name: voyageur-network
    driver: bridge